# Generated by Django 4.2.11 on 2024-03-29 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstQuest', models.CharField(max_length=128)),
                ('secondtQuest', models.CharField(max_length=128)),
                ('name', models.CharField(max_length=128)),
                ('phone', models.CharField(max_length=20)),
            ],
        ),
    ]
